(function(){
  "use strict";
  const DATA_URL="notifications.json";
  const page=(document.body.dataset.notificationPage||"").trim();
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const norm=v=>String(v??"").trim().toLowerCase().replace(/&/g,"and").replace(/\s+/g," ");
  function parseDate(v){const s=String(v??"").trim();if(!s)return null;let m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(m)return new Date(+m[3],+m[2]-1,+m[1],23,59,59,999);m=s.match(/^(\d{4})[\/-](\d{1,2})[\/-](\d{1,2})$/);if(m)return new Date(+m[1],+m[2]-1,+m[3],23,59,59,999);const n=Number(s);if(Number.isFinite(n)&&n>20000&&n<80000){const d=new Date(Date.UTC(1899,11,30)+n*86400000);return new Date(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),23,59,59,999)}const d=new Date(s.replace(/\bSept\b/i,"Sep").replace(/\./g,""));return Number.isNaN(d.getTime())?null:new Date(d.getFullYear(),d.getMonth(),d.getDate(),23,59,59,999)}
  const end=r=>parseDate(r.applicationEnd||r.end||r.date);
  const result=r=>/result|admit\s*card|answer\s*key|selection|allocation|call\s*letter|hall\s*ticket/i.test([r.type,r.category,r.title,r.status].map(norm).join(" "));
  const active=r=>{const s=norm(r.status);if(/closed|expired|over|withdrawn|cancelled/.test(s))return false;const e=end(r);return !e||e>=new Date()};
  const latest=r=>{if(result(r))return false;const blob=[r.type,r.category,r.title,r.status].map(norm).join(" ");const open=/open|live|active|apply|application|recruitment|notification|engagement/.test(blob);const e=end(r);return active(r)&&(norm(r.portal_category)==="latest-notifications"||(e&&e>=new Date()&&(open||norm(r.type)==="job"||/recruit|vacanc|job|application|engagement/.test(norm(r.category)))))};
  const upcoming=r=>{if(result(r)||latest(r)||!active(r))return false;if(norm(r.portal_category)==="upcoming-exams")return true;return /upcoming\s*exam|exam\s*calendar|scheduled\s*exam/i.test([r.type,r.category,r.title,r.status].map(norm).join(" "))};
  function detailLink(r){return "job-detail.html?title="+encodeURIComponent(String(r.title||""))}
  function dateText(r){const s=String(r.applicationStart||"").trim(),e=String(r.applicationEnd||"").trim();return s&&e&&s!==e?s+" – "+e:(e||s||String(r.date||""))}
  function card(r){const c=document.createElement("article");c.className="notice-item";const d=dateText(r);const status=esc(r.status||"OPEN");c.innerHTML='<div class="notice-main"><h2><a href="'+esc(detailLink(r))+'">'+esc(r.title)+'</a></h2><div class="meta"><span>'+esc(r.type||"Notification")+'</span><span>'+esc(r.state||"")+'</span>'+(r.category?'<span>'+esc(r.category)+'</span>':'')+(d?'<span>'+esc(d)+'</span>':'')+'<span>'+status+'</span></div></div><a class="details" href="'+esc(detailLink(r))+'">View Details →</a>';return c}
  fetch(DATA_URL+"?v="+Date.now(),{cache:"no-store"}).then(r=>{if(!r.ok)throw Error("HTTP "+r.status);return r.json()}).then(rows=>{rows=Array.isArray(rows)?rows:[];let f=page==="latest"?rows.filter(latest):page==="upcoming"?rows.filter(upcoming):rows.filter(result);f.sort((a,b)=>(end(b)?.getTime()||0)-(end(a)?.getTime()||0));document.getElementById("count").textContent=f.length+" notifications";const list=document.getElementById("list");if(!f.length){list.innerHTML='<div class="empty">No notifications available in this category.</div>';return}f.forEach(r=>list.appendChild(card(r)))}).catch(e=>{console.error(e);document.getElementById("list").innerHTML='<div class="empty">Notifications are temporarily unavailable.</div>'});
})();
